# Generated by Django 5.2.8 on 2025-11-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicOrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stduentmodel',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
