print(
    '''
    *********************
    *  Range in Python  *
    ********************* 
    '''
)
print("\n")
print("Range with one arguments.....")
x=range(10)
print(x)
print(list(x))
print("\n")
print("Range with Two Arguments....")
y=range(3,10)
print(y)
print(list(y))
print("\n")
print("Range with Three Arguments....")
z=range(3,10,2)
print(z)
print(list(z))
print("\n")
print("Using Range Function....")
for i in range(10):
    print(i)
print("\n")
print("Using List to Display Ranges.....")
print(list(range(5)))
print(list(range(1,6)))
print(list(range(1,8,2)))
print("\n")
x=range(10)
print(x[2])
print(x[:3])
print("\n")
print("Membership Testing.....")
r=range(0,10,2)
print(6 in r)
print(7 in r)
print("\n")
print("Lenght in Python......")
e=range(0,10,2)
print(len(e))
