# Generated by Django 5.2.8 on 2025-11-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='is_completed',
        ),
    ]
