# Generated by Django 5.2.7 on 2025-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('describe', models.TextField()),
            ],
        ),
    ]
