# Generated by Django 5.2.8 on 2025-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.FloatField()),
                ('result', models.BooleanField()),
            ],
        ),
    ]
