# Generated by Django 5.2.7 on 2025-10-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('tob', models.TimeField()),
                ('dat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
